### ISSUE TITLE
Index out of bounds error when printing lexemes

### ISSUE THREAD

**Issue by RandomMurican** [RandomMurican/Lexalyzer#2]
prints all of desired data and then spews out this:

Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 13, Size: 13
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.randommurican.Lexalyser.MiniLang.next(MiniLang.java:101)
	at com.randommurican.Lexalyser.Driver.main(Driver.java:41)

**Comment by RandomMurican** [comment]
fixed.
